use_frameworks!

platform :ios, '9.0'

target 'JJBundle_Example' do
  pod 'JJBundle', :path => '../'

  target 'JJBundle_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
